name: Build and Release Magisk Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up zip
        run: sudo apt-get install zip

      - name: Create META-INF files
        run: |
          mkdir -p META-INF/com/google/android
          echo "#MAGISK" > META-INF/com/google/android/updater-script
          wget https://raw.githubusercontent.com/topjohnwu/Magisk/refs/heads/master/scripts/module_installer.sh -O META-INF/com/google/android/update-binary
          chmod +x META-INF/com/google/android/update-binary

      - name: Package Magisk Module
        run: zip -r9 magisk-lan-auto-switch.zip ./ -x ".github/*" ".git/*"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: magisk-lan-auto-switch
          path: magisk-lan-auto-switch.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: magisk-lan-auto-switch
          path: .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: magisk-lan-auto-switch.zip
